### ISSUE TITLE
Not working at all after any restart

### ISSUE THREAD

**Issue by usamaiqbal1177** [jozein/Xposed-edge-translation#14]
@jozein 

Hello. Whenever I restart all the gestures and settings of xposed edge stops working. I have to manually change individual settings to some other and then back to what I want. Then it works. But it takes too much time to configure everything. It happens after I restart. Restoring backup doesn't help

Xposed Edge Log:
0000:00:16.235  Xposed edge pro 5.5.5, activated by EdXposed. 
  Xiaomi Redmi Note 4, mido, Android 10, SDK 29, ROM: QQ1B.200105.004
0000:00:16.736  System hooked
0000:00:24.958  init
0000:00:24.959  Screen size: 1080, 1920
0000:00:24.867  System booted.
0000:00:28.033  Module initialed.

@jozein

**Comment by usamaiqbal1177** [comment]
@jozein can u please help resolve this. I cannot find you in tg group. I can provide boot logs or any other logs too if you want, broh.

**Comment by shmykelsa** [comment]
Having the same issue. Many people on XDA too.

**Comment by jozein** [comment]
Could you please try another version of EdXposed?

**Comment by usamaiqbal1177** [comment]
> Could you please try another version of EdXposed?

Broh, I tried in alpha version of EdXposed 4471
Doesn't work on that also.
I use latest canary build 4504 by MlgmXyssd

**Comment by shmykelsa** [comment]
Could it be that this bug is specific to Android 10? Because I've got Android 10 too and many people claiming this issue have Android 10

**Comment by usamaiqbal1177** [comment]
@jozein the new update 5.5.6 has fixed that issue. Thanks a lot for your work. Much appreciated!
